"""rename_expense_date

Revision ID: 37f969dd0def
Revises: 739a75aa8416
Create Date: 2026-04-18 17:13:04.790636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f969dd0def'
down_revision: Union[str, None] = '739a75aa8416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('expense_date', sa.Date(), nullable=False))
    op.drop_column('expenses', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('expenses', 'expense_date')
    # ### end Alembic commands ###
